name: assets_builder
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build:
  source_gen:
  path:
  glob:

dev_dependencies:
  build_runner:
  pedantic: ^1.8.0
  test: ^1.6.0
